<?php

/**
 * @file
 * Contains entity_booking.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_booking_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_booking module.
    case 'help.page.entity_booking':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test Entity Booking') . '</p>';
      return $output;

    default:
  }
}
